name: 'feedback'
description: 'Send an email to someone who appreciates you'
inputs:
  repo:
    description: 'repo'
    required: true
    default: 'd2-projects/d2-admin'
  actor:
    description: 'actor'
    required: true
    default: 'FairyEver'
  token:
    description: 'token'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'