name: 'feedback'
description: 'Send an email to someone who appreciates you'
inputs:
  username:
    description: 'username'
    required: true
    default: ''
  sign:
    description: 'sign'
    required: true
    default: ''
  to:
    description: 'to some one'
    required: false
    default: ''
  actor:
    description: 'actor'
    required: false
    default: ''
  token:
    description: 'token'
    required: false
    default: ''
  template:
    description: 'template'
    required: false
    default: ''
  repo:
    description: 'repo'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'